#!/bin/bash

# user level python
PY_VERSION="${PY_VERSION:-3.13}"
PY_EXEC="python${PY_VERSION}"
PY_HOME="${HOME}/.py${PY_VERSION}"
PIP_EXEC="pip${PY_VERSION}"

# colors
export COLOR_RED='\033[0;31m'
export COLOR_YELLOW='\033[1;33m'
export COLOR_GREEN='\033[0;32m'
export COLOR_BLUE='\033[1;34m'
export COLOR_CYAN='\033[0;36m'
export COLOR_LIGHT_RED='\033[1;31m'
export COLOR_NONE='\033[0m'

check_platform (){
    if [[ "$OSTYPE" == "linux"* ]]; then
        distro_id=`lsb_release -d`

        if [[ "$distro_id" == *"Debian"* ]]; then
            export os_platform="debian"
        elif [[ "$distro_id" == *"Ubuntu"* ]]; then
            export os_platform="debian"
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        export os_platform="osx"
    fi
}

check_platform

user_confirm (){
    prompt="${1}"
    defval="${2:-n}"

    read -p "$(echo -e "${COLOR_BLUE}${prompt} Continue? (y/n)${COLOR_NONE} ")" -n 1 -r confirm_result
    echo
    if [[ $confirm_result != "y" ]] && [[ $confirm_result != "Y" ]]; then
        exit 1
    fi
}

export LOCAL_BIN_PATH="${HOME}/local/bin"
mkdir -p $LOCAL_BIN_PATH
