source ~/.profile0
bindkey \^U backward-kill-line

export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt hist_find_no_dups
setopt no_share_history
setopt inc_append_history

__git_files () {
    _wanted files expl 'local files' _files
}

export DISABLE_MAGIC_FUNCTIONS=true
