#!/bin/bash
COLOR_RED='\033[0;31m'
COLOR_YELLOW='\033[1;33m'
COLOR_GREEN='\033[0;32m'
COLOR_BLUE='\033[1;34m'
COLOR_CYAN='\033[0;36m'
COLOR_LIGHT_RED='\033[1;31m'
COLOR_NONE='\033[0m'

dry_run=1
if [[ $1 = "--no-dry-run" ]]; then
    dry_run=0
fi

if which gdate &>/dev/null; then
    datecmd="gdate"
else
    datecmd="date"
fi

BRANCH_EXPIRE_DAYS=${BRANCH_EXPIRE_DAYS:-30}
PROTECTED_BRANCHES=${PROTECTED_BRANCHES:-master,main}

IFS=',' read -r -a protected_branches_array <<< "$PROTECTED_BRANCHES"

today=`${datecmd} '+%Y-%m-%d'`
branches_to_be_removed=()

for br in `git branch | cut -c 3-`; do
    is_protected=0
    for pbr in "${protected_branches_array[@]}"; do
        if [[ $br = $pbr ]]; then
            is_protected=1;
        fi
    done

    if [[ $is_protected = "1" ]]; then
        continue
    fi

    br_last_modified=$(git show --no-patch --no-notes --pretty='%cd' --date=short $(git rev-parse $br))
    days_after_last_modified=`echo $((($(${datecmd} -d "${today}" +%s) - $(${datecmd} -d "${br_last_modified}" +%s))/86400))`

    if [[ $days_after_last_modified -lt ${BRANCH_EXPIRE_DAYS} ]]; then
        continue
    fi

    branches_to_be_removed+=("$br")
done

if [[ $dry_run = "1" ]]; then
    echo "Dry run mode enabled"
    echo "Branches to be removed:"
    for br in "${branches_to_be_removed[@]}"; do
        echo -e "${COLOR_YELLOW}  " $br " ${COLOR_NONE}"
    done
    echo -e "Run${COLOR_RED} git_do_clean --no-dry-run ${COLOR_NONE}to take effect"
else
    echo -e "${COLOR_GREEN}Delete branches${COLOR_NONE}"
    for br in "${branches_to_be_removed[@]}"; do
        git branch -D $br
    done
    echo -e "${COLOR_GREEN}Run git gc${COLOR_NONE}"
    git gc --aggressive
    echo "Done"
fi

